substitutions:
  id: k062hx # Generated a random hex - https://numbergenerator.org/hex-code-generator
  name: parking-meter-basic
  friendly_name: Parking Distance Meter v3
  
  # GPIO Pin assignments
  echo_pin: GPIO5   # D1 on D1 Mini
  trigger_pin: GPIO4 # D2 on D1 Mini
  dio_pin: GPIO12   # D6 on D1 Mini
  clk_pin: GPIO13   # D7 on D1 Mini

  # Settings
  update_interval: "0.05s"
  display_intensity: "7"
  
  # Security
  wifi_fallback_password: "M0gj8OUiQCbA" # Set the wifi fallback password
  ota_password: "72f3769daa87b8b198f86d1f0a49a92d" 
  encryption_key: "zs6xnOerLgnyq2ab6RhoBJeaQa7hVgIzntAs4xAMO40="

esphome:
  name: ${name}-${id}
  friendly_name: ${friendly_name} ${id}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ${encryption_key}

ota:
  - platform: esphome
    password: ${ota_password}

improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Parking Sensor ${id} Fallback"
    password: ${wifi_fallback_password}

captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

sensor:
  - platform: ultrasonic
    trigger_pin: ${trigger_pin}
    echo_pin: ${echo_pin}
    id: distance_sensor
    name: "Distance"
    update_interval: ${update_interval}
    unit_of_measurement: "m"
    accuracy_decimals: 3

display:
  - platform: tm1637
    id: led_display
    clk_pin: ${clk_pin}
    dio_pin: ${dio_pin}
    update_interval: ${update_interval}
    intensity: ${display_intensity}
    lambda: |-
      float distance_m = id(distance_sensor).state;
      if (isnan(distance_m)) {
        it.print("----");
      } else {
        it.printf("%4.0f", distance_m * 100.0);
      }