substitutions:
  id: k062hx # Generated a random hex - https://numbergenerator.org/hex-code-generator
  name: parking-meter-basic
  friendly_name: Parking Distance Meter v3
  
  # GPIO Pin assignments
  echo_pin: GPIO5   # D1 on D1 Mini
  trigger_pin: GPIO4 # D2 on D1 Mini
  dio_pin: GPIO12   # D6 on D1 Mini
  clk_pin: GPIO13   # D7 on D1 Mini

  # Settings
  update_interval: "0.1s"
  display_intensity: "7"
  
  # Security
  wifi_fallback_password: "M..A" # Set the wifi fallback password
  ota_password: "7..d" 
  encryption_key: "z..="

esphome:
  name: ${name}-${id}
  friendly_name: ${friendly_name} ${id}
  min_version: 2024.6.0

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ${encryption_key}

ota:
  - platform: esphome
    password: ${ota_password}

improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Parking Sensor ${id} Fallback"
    password: ${wifi_fallback_password}

captive_portal:


sensor:
  - platform: ultrasonic
    id: ultrasonic_distance
    trigger_pin: ${trigger_pin}
    echo_pin: ${echo_pin}
    name: "${friendly_name} Distance"
    unit_of_measurement: "m"
    update_interval: ${update_interval}
    # timeout defaults to sensor max range (~2m). Adjust if needed.
    timeout: 2m
    accuracy_decimals: 3

# TM1637 display configuration to show the raw sensor reading
display:
  - platform: tm1637
    id: led_display
    clk_pin: ${clk_pin}
    dio_pin: ${dio_pin}
    intensity: ${display_intensity}
    update_interval: ${update_interval}
    lambda: |-
      float distance_m = id(ultrasonic_distance).state;
      if (isnan(distance_m)) {
        it.print("----");
      } else {
        it.printf("%4.0f", distance_m * 100.0);
      }